version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "80:8000"
    environment:
      - API_BASE_URL=$API_BASE_URL

  back:
    build:
      context: .
      dockerfile: Dockerfile.back
    ports:
      - "8001:8001"
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_SCHEME=$DB_SCHEME
